/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerFillProductDataResponse
 */
export interface AiproductdataenhancerFillProductDataResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AiproductdataenhancerFillProductDataResponse
     */
    'productDataFilled'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof AiproductdataenhancerFillProductDataResponse
     */
    'confidenceRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof AiproductdataenhancerFillProductDataResponse
     */
    'completionRate'?: number;
}
