/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerFillProductDataCheckResponse
 */
export interface AiproductdataenhancerFillProductDataCheckResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AiproductdataenhancerFillProductDataCheckResponse
     */
    'productDataFilled'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof AiproductdataenhancerFillProductDataCheckResponse
     */
    'confidenceRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof AiproductdataenhancerFillProductDataCheckResponse
     */
    'completionRate'?: number;
    /**
     * 
     * @type {AiproductdataenhancerJobStatus}
     * @memberof AiproductdataenhancerFillProductDataCheckResponse
     */
    'status'?: AiproductdataenhancerJobStatus;
    /**
     * 
     * @type {AiproductdataenhancerError}
     * @memberof AiproductdataenhancerFillProductDataCheckResponse
     */
    'error'?: AiproductdataenhancerError;
}
