/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerDataToTranslate
 */
export interface AiproductdataenhancerDataToTranslate {
    /**
     * 
     * @type {string}
     * @memberof AiproductdataenhancerDataToTranslate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AiproductdataenhancerDataToTranslate
     */
    'value'?: string;
}
