/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerTranslateDataRequest
 */
export interface AiproductdataenhancerTranslateDataRequest {
    /**
     * 
     * @type {string}
     * @memberof AiproductdataenhancerTranslateDataRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {AiproductdataenhancerLanguageCode}
     * @memberof AiproductdataenhancerTranslateDataRequest
     */
    'targetLanguage'?: AiproductdataenhancerLanguageCode;
    /**
     * 
     * @type {AiproductdataenhancerLanguageCode}
     * @memberof AiproductdataenhancerTranslateDataRequest
     */
    'sourceLanguage'?: AiproductdataenhancerLanguageCode;
    /**
     * 
     * @type {Array<AiproductdataenhancerDataToTranslate>}
     * @memberof AiproductdataenhancerTranslateDataRequest
     */
    'dataToTranslate'?: Array<AiproductdataenhancerDataToTranslate>;
}
