/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerProductDataToFill
 */
export interface AiproductdataenhancerProductDataToFill {
    /**
     * 
     * @type {string}
     * @memberof AiproductdataenhancerProductDataToFill
     */
    'name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AiproductdataenhancerProductDataToFill
     */
    'valueSet'?: Array<string>;
    /**
     * Metadata is an optional field to provide additional information to the AI like, max length, min length, field description, etc.
     * @type {{ [key: string]: string; }}
     * @memberof AiproductdataenhancerProductDataToFill
     */
    'metadata'?: { [key: string]: string; };
}
