/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AiproductdataenhancerFillProductDataRequest
 */
export interface AiproductdataenhancerFillProductDataRequest {
    /**
     * 
     * @type {string}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {AiproductdataenhancerLanguageCode}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'languageCode'?: AiproductdataenhancerLanguageCode;
    /**
     * 
     * @type {AiproductdataenhancerProductInformation}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'productInformation'?: AiproductdataenhancerProductInformation;
    /**
     * 
     * @type {Array<string>}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'productDataToFill'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'domainsToInclude'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AiproductdataenhancerFillProductDataRequest
     */
    'domainsToExclude'?: Array<string>;
}
