/* tslint:disable */
/* eslint-disable */
/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AiproductdataenhancerJobStatus = {
    Unknown: 'JOB_STATUS_UNKNOWN',
    Pending: 'JOB_STATUS_PENDING',
    Running: 'JOB_STATUS_RUNNING',
    Completed: 'JOB_STATUS_COMPLETED',
    Failed: 'JOB_STATUS_FAILED'
} as const;
export type AiproductdataenhancerJobStatus = typeof AiproductdataenhancerJobStatus[keyof typeof AiproductdataenhancerJobStatus];


export function AiproductdataenhancerJobStatusFromJSON(json: any): AiproductdataenhancerJobStatus {
    return AiproductdataenhancerJobStatusFromJSONTyped(json, false);
}

export function AiproductdataenhancerJobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiproductdataenhancerJobStatus {
    return json as AiproductdataenhancerJobStatus;
}

export function AiproductdataenhancerJobStatusToJSON(value?: AiproductdataenhancerJobStatus | null): any {
    return value as any;
}

