/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AiproductdataenhancerDataToTranslate } from '../models/AiproductdataenhancerDataToTranslate';
import { AiproductdataenhancerLanguageCode } from '../models/AiproductdataenhancerLanguageCode';
import { HttpFile } from '../http/http';

export class AiproductdataenhancerTranslateDataRequest {
    'tenantId'?: string;
    'targetLanguage'?: AiproductdataenhancerLanguageCode;
    'sourceLanguage'?: AiproductdataenhancerLanguageCode;
    'dataToTranslate'?: Array<AiproductdataenhancerDataToTranslate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetLanguage",
            "baseName": "targetLanguage",
            "type": "AiproductdataenhancerLanguageCode",
            "format": ""
        },
        {
            "name": "sourceLanguage",
            "baseName": "sourceLanguage",
            "type": "AiproductdataenhancerLanguageCode",
            "format": ""
        },
        {
            "name": "dataToTranslate",
            "baseName": "dataToTranslate",
            "type": "Array<AiproductdataenhancerDataToTranslate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AiproductdataenhancerTranslateDataRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



