/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AiproductdataenhancerLanguageCode } from '../models/AiproductdataenhancerLanguageCode';
import { AiproductdataenhancerProductInformation } from '../models/AiproductdataenhancerProductInformation';
import { HttpFile } from '../http/http';

export class AiproductdataenhancerFillProductDataRequest {
    'tenantId'?: string;
    'languageCode'?: AiproductdataenhancerLanguageCode;
    'productInformation'?: AiproductdataenhancerProductInformation;
    'productDataToFill'?: Array<string>;
    'domainsToInclude'?: Array<string>;
    'domainsToExclude'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "languageCode",
            "baseName": "languageCode",
            "type": "AiproductdataenhancerLanguageCode",
            "format": ""
        },
        {
            "name": "productInformation",
            "baseName": "productInformation",
            "type": "AiproductdataenhancerProductInformation",
            "format": ""
        },
        {
            "name": "productDataToFill",
            "baseName": "productDataToFill",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "domainsToInclude",
            "baseName": "domainsToInclude",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "domainsToExclude",
            "baseName": "domainsToExclude",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AiproductdataenhancerFillProductDataRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



