/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum AiproductdataenhancerJobStatus {
    Unknown = 'JOB_STATUS_UNKNOWN',
    Pending = 'JOB_STATUS_PENDING',
    Running = 'JOB_STATUS_RUNNING',
    Completed = 'JOB_STATUS_COMPLETED',
    Failed = 'JOB_STATUS_FAILED'
}
