/**
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AiproductdataenhancerError } from '../models/AiproductdataenhancerError';
import { AiproductdataenhancerJobStatus } from '../models/AiproductdataenhancerJobStatus';
import { HttpFile } from '../http/http';

export class AiproductdataenhancerFillProductDataCheckResponse {
    'productDataFilled'?: { [key: string]: string; };
    'confidenceRate'?: number;
    'completionRate'?: number;
    'status'?: AiproductdataenhancerJobStatus;
    'error'?: AiproductdataenhancerError;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productDataFilled",
            "baseName": "productDataFilled",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "confidenceRate",
            "baseName": "confidenceRate",
            "type": "number",
            "format": "float"
        },
        {
            "name": "completionRate",
            "baseName": "completionRate",
            "type": "number",
            "format": "float"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AiproductdataenhancerJobStatus",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "AiproductdataenhancerError",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AiproductdataenhancerFillProductDataCheckResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



